name: Merge Develop to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  merge-develop-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name 'GeoVerde Bot'
          git config --global user.email 'bot@geoverde.com'

      - name: Merge develop into main
        run: |
          git checkout develop
          git pull origin develop
          git checkout main
          git pull origin main
          git merge develop
          git push origin main
